# USER INPUT FOR 3D GND CALCULATIONS
# No quotes around paths, directories need a "/" at the end

[PARAMS]

# path to DREAM3D h5 file
DREAM3D File = [PATH TO .dream3d FILE]

# directory where to save the output files
Save Folder = [PATH TO DIRECTORY WHERE OUTPUT IS SAVED]

# Dataset name to use when saving the outputs
ID = [NAME OF EXPERIMENT]

# Burgers vector of the system
Burgers = [BURGERS VECTOR, 2.48 for CoNi]

# Crystal structure of the material
Crystallography = [ONE OF fcc, bcc, hcp]

# Additional information about the active slip planes (relevant for BCC and HCP) DO NOT PUT QUOTES AROUND THE VALUES
# For FCC: None (it is ignored)
# For BCC: 'screw + 110', 'screw + 112', 'screw + 123', 'screw + 110 + 112', 'all'
# HCP: 'basal', 'basal + prismatic', 'all'
Slip systems = None
