# USER INPUT FOR 2D GND CALCULATIONS
# No quotes around paths, directories need a "/" at the end

[PARAMS]

# path to DREAM3D h5 file
ANG File = E:/DED_CoNi.ang

# directory where to save the output files
Save Folder = E:/

# Dataset name to use when saving the outputs
ID = DED_CoNi

# Burgers vector of the system
Burgers = 2.48

# Crystal structure of the material
Crystallography = fcc

# Additional information about the active slip planes (relevant for BCC and HCP) DO NOT PUT QUOTES AROUND THE VALUES
# For FCC: None (it is ignored)
# For BCC: 'screw + 110', 'screw + 112', 'screw + 123', 'screw + 110 + 112', 'all'
# HCP: 'basal', 'basal + prismatic', 'all'
Slip systems = None
