[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "pygnd"
dynamic = ["version"]
description = "GND calculations for TriBeam 3D microstructures using dislocation theory"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    {name = "James Lamb", email = "lambjames18@gmail.com"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

dependencies = [
    "numpy",
    "scipy",
    "h5py",
    "matplotlib",
    "tqdm",
    "joblib",
]

[dependency-groups]
dev = [
    "pylint",
    "pylint-exit",
    "pytest",
    "pytest-cov",
    "pdoc",
]

[project.scripts]
pygnd_gui = "pygnd.gui:main"
pygnd_calculate = "pygnd.cli:main"
pygnd = "pygnd.cli:info"

[project.urls]
Homepage = "https://github.com/lambjames18/pyGND"
Repository = "https://github.com/lambjames18/pyGND"
Issues = "https://github.com/lambjames18/pyGND/issues"
Documentation = "https://lambjames18.github.io/pyGND/api/"

# ----------------------
# Hatch Configuration
# ----------------------

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"  # Ensures clean versions like 0.0.9 instead of 0.0.9+g1234567

[tool.hatch.build.targets.wheel]
packages = ["src/pygnd"]

[tool.hatch.build.hooks.vcs]
version-file = "src/pygnd/_version.py"  # File to be generated when compiled

# ----------------------
# Pytest Configuration
# ----------------------

[tool.pytest.ini_options]
python_files = ["test_*.py", "*_test.py"]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = "--cov=src/pygnd --cov-report=term-missing -rs"

# ----------------------
# Coverage Configuration
# ----------------------

[tool.coverage.run]  # Coverage is used for test coverage reports
branch = true
relative_files = true
source = ["src"]
omit = ["*/tests/*", "*/__pycache__/*", "gui.py"]

[tool.coverage.paths]
pygnd = [
    "src/pygnd",
]

[tool.coverage.report]  # Coverage is used for test coverage reports
show_missing = true  # Show which lines were not covered
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
    "raise NotImplementedError",
]

[tool.coverage.html]
directory = "coverage_reports/combined/htmlcov"

[tool.coverage.xml]
output = "coverage_reports/combined/coverage.xml"
