name: CI (Continuous Integration)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

# Concurrency ensures that if you push again while a build is already running, the old one is canceled.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Lint and Test (pylint, pytest)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Announce workflow file
        run: |
          echo "Workflow file: ${{ github.workflow_ref }}"

      - name: Checkout code
        uses: actions/checkout@v6
        with:
            fetch-depth: 0 # Fetch all history for accurate linting and testing, required for hatch-vcs to determine version from tags
            fetch-tags: true # Ensure tags are fetched for accurate versioning, required for hatch-vcs to determine version from tags

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.8.12'
          enable-cache: true
          #cache-dependency-glob: "pyproject.toml"  # Delete this line after 'uv lock' run locally is used to create a uv.lock file, then uv.lock, the default, will be used for caching dependencies

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build Check
        run: uv build

      - name: Run Pylint and Create Pylint Report
        run: |
          uv run pylint src/pytribeam > report_lint.txt || true

      - name: Upload Pylint Report
        uses: actions/upload-artifact@v7
        with:
          name: report-lint
          path: report_lint.txt

      - name: Run Pytest 
        if: ${{ hashFiles('.coverage') == '' }}
        run: |
          uv run pytest -v --cov=pygnd --cov-report=xml --cov-report=term

      - name: Upload HTML Coverage Artifact
        uses: actions/upload-artifact@v7
        with:
          name: report-coverage
          path: |
            htmlcov/
            report_coverage.xml


  api-docs:
    name: Build API Documentation with pdoc
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    permissions:
      contents: read
      packages: read

    steps:
      - name: Announce workflow file
        run: |
          echo "Workflow file: ${{ github.workflow_ref }}"

      - name: Checkout code
        uses: actions/checkout@v6
        with:
            fetch-depth: 0 # Fetch all history for accurate linting and testing, required for hatch-vcs to determine version from tags
            fetch-tags: true # Ensure tags are fetched for accurate versioning, required for hatch-vcs to determine version from tags

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.8.12'
          enable-cache: true
          #cache-dependency-glob: "pyproject.toml"  # Delete this line after 'uv lock' run locally is used to create a uv.lock file, then uv.lock, the default, will be used for caching dependencies

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build Check
        run: uv build
